name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Authenticate with npm
        run: npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}

      - name: Install dependencies
        run: npm i

      - name: Building the project
        run: npm run build
      - name: Copy package.json
        run: cp npm-publish.json ./build/package.json
      - name: Copy LICENSE
        run: cp LICENSE ./build/LICENSE
      - name: Copy Readme
        run: cp npm-readme.md ./build/Readme.md
      - name: Publish to npm
        run: |
          cd ./build
          npm publish